@startuml casos de uso
left to right direction

actor Recepcionista
actor Medico
actor Administrador
actor Paciente

rectangle "Sistema de Gestión Hospitalaria" {

  usecase "Registrar Paciente" as CU01
  usecase "Agendar Cita Médica" as CU02
  usecase "Atender Paciente" as CU03
  usecase "Contratar Empleado" as CU04
  usecase "Cancelar Cita" as CU05
  usecase "Consultar Historial Médico" as CU06

}

Recepcionista --> CU01
Recepcionista --> CU02
Recepcionista --> CU06
Recepcionista --> CU05

Medico --> CU03

Administrador --> CU04

Paciente --> CU05
Paciente --> CU06

@enduml