@startuml Diagrama clases 

' =========================
' PAQUETES
' =========================
package modelo.abstractas {
    
    abstract class Persona {
        - id : String
        - nombre : String
        - apellido : String
        - fechaNacimiento : LocalDate
        - email : String

        + calcularEdad() : int
        + obtenerTipo() : String
        + getNombre() : String
    }

    abstract class Empleado {
        - legajo : String
        - fechaContratacion : LocalDate
        - salarioBase : double
        - activo : boolean

        + antiguedad() : int
        + calcularSalario() : double
        + getSalarioBase() : double
        + setSalarioBase(double)
    }

    Persona <|-- Empleado
}

package modelo.personas {

    class Medico {
        - especialidad : String

        + calcularSalario() : double
        + obtenerTipo() : String
    }

    class Cirujano {
        - cirugiasRealizadas : int

        + calcularSalario() : double
        + obtenerTipo() : String
    }

    class Enfermero {
        - turno : String

        + calcularSalario() : double
        + obtenerTipo() : String
    }

    class Paciente {
        - grupoSanguineo : String
        - alergias : List<String>

        + agregarAlergia(String)
        + getAlergias() : List<String>
        + obtenerTipo() : String
    }

    Empleado <|-- Medico
    Medico <|-- Cirujano
    Empleado <|-- Enfermero
    Persona <|-- Paciente
}

package modelo.hospital {

    class CitaMedica {
        - paciente : Paciente
        - medico : Medico
        - fecha : LocalDateTime
        - estado : EstadoCita

        + completar()
        + cancelar()
    }
}

package principal {

    class SistemaHospitalDemo {
        - sc : Scanner
        - hospital : Hospital
        - pacientes : List<Paciente>
        - medicos : List<Medico>
        - citas : List<CitaMedica>

        + main(String[]) 
        - registrarEmpleado()
        - registrarPaciente()
        - mostrarPacientes()
        - agendarCita()
        - mostrarCitas()
        - cambiarEstadoCita()
        - crearMedico() : Medico
        - crearCirujano() : Cirujano
        - crearEnfermero() : Enfermero
    }
}

' =========================
' RELACIONES
' =========================

CitaMedica --> Paciente
CitaMedica --> Medico

SistemaHospitalDemo --> Paciente
SistemaHospitalDemo --> Medico
SistemaHospitalDemo --> CitaMedica

@enduml
