@startuml de_clases 
' =========================
' CLASES ABSTRACTAS
' =========================

abstract class Persona {
    -id: int
    -nombre: String 
    -apellido: String
    -fechaNacimiento: LocalDate
    -email: String
    +calcularEdad(): int
    +obtenerTipo(): String
}

abstract class Empleado {
    -legajo: String
    -fechaContratacion: LocalDate
    -salarioBase: double
    -activo: boolean
    +calcularSalario(): double
    +antiguedad(): int
}

' =========================
' PERSONAS
' =========================

class Paciente {
    -historiaClinicaID: String
    -grupoSanguineo: String
    -alergias: List<String>
    +agregarAlergia()
    +obtenerHistorial()
}

class Medico {
    -numeroLicencia: String
    -especialidad: String
    +atenderPaciente()
    +calcularSalario()
}

class Cirujano {
    -cirugiasRealizadas: int
    -disponibilidadEmergencias: boolean
    +realizarCirugia()
    +calcularBono()
}

class Enfermero {
    -turno: Turno
    -areaAsignada: String
    +asistirCirujia()
    +calcularSalario()
}

' =========================
' HOSPITAL
' =========================

class Hospital {
    -nombre: String 
    -direccion: String
    -empleados: List<Empleado>
    -pacientes: List<Paciente>
    +contratarEmpleado()
    +agendarCita()
    +calcularNominaTotal()
}

class citaMedica {
    -id: int
    -fechaHora: LocalDateTime
    -motivo: String
    -estado: EstadoCita
    +calcularCosto()
    +compeletar()
    +cancelar()
}

class Diagnostico {
    -id: int
    -descripcion: String
    -fecha: LocalDate
    -receta: LocalDate
}

class especialidad {
    -codigo: String
    -nombre: String
    -costoConsulta: double
}

' =========================
' ENUMS
' =========================

enum EstadoCita {
    PENDIENTE
    CONFIRMADA
    EN_ATENCION
    COMPLETADA
    CANCELADA
}

enum Turno {
    MAÑANA
    TARDE
    NOCHE
}

' =========================
' RELACIONES
' =========================

Persona <|-- Paciente
Persona <|-- Paciente
Empleado <|-- Medico
Medico <|-- Cirujano
Empleado <|-- Enfermero

Hospital "1" *-- "*" Empleado
Hospital "1" *-- "*" Paciente
Hospital "1" *-- "*" citaMedica

citaMedica --> Paciente 
citaMedica --> Medico
citaMedica --> Diagnostico

Medico --> especialidad

@enduml
